### ISSUE TITLE
Couldn't find index page for 'jsbeautifier'

### ISSUE THREAD

**Issue by rmjaadugar** [GerbenJavado/LinkFinder#115]
I am unable to find any jsbeautifier in the dependencies list and I am getting below error while trying to setup. Any helping tip to overcome this issue.

Installed /usr/local/lib/python3.9/dist-packages/LinkFinder-1.0-py3.9.egg
Processing dependencies for LinkFinder==1.0
Searching for jsbeautifier
Reading https://pypi.org/simple/jsbeautifier/
Download error on https://pypi.org/simple/jsbeautifier/: [Errno -3] Temporary failure in name resolution -- Some packages may not be found!
Couldn't find index page for 'jsbeautifier' (maybe misspelled?)

**Comment by ville87** [comment]
You have to install it first with pip:
`$ pip3 install jsbeautifier`
