### ISSUE TITLE
DeprecationWarning: ssl.PROTOCOL_TLSv1_2

### ISSUE THREAD

**Issue by okondo-afo** [GerbenJavado/LinkFinder#122]
linkfinder returns this output 

/LinkFinder/linkfinder.py:133: DeprecationWarning: ssl.PROTOCOL_TLSv1_2 is deprecated
  sslcontext = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
cat: standard output: Bad file descriptor

**Comment by pro7357** [comment]
Yeah, ssl.PROTOCOL_TLSv1_2 is deprecated.
Referring to https://docs.python.org/3/library/ssl.html#client-side-operation, update those line with:
sslcontext = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
sslcontext.load_verify_locations("/etc/ssl/certs/ca-bundle.crt")

I didn't have that cert. But cert from ncat work fine. I'm using /usr/share/ncat/ca-bundle.crt

**Comment by abhinavsaraswatt** [comment]
above thing didn't work for me

**Comment by gprime31** [comment]
python -W ignore foo.py

**Comment by Incend1um** [comment]
for MacOS this worked for me
sslcontext = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
sslcontext.load_verify_locations("/usr/local/Cellar/nmap/7.92/share/ncat/ca-bundle.crt")

**Comment by abhinavsaraswatt** [comment]
> python -W ignore foo.py

This works for me!

**Comment by Guymosciski** [comment]
guys i am a little beginner here could someone please help me a bit more clear on how to clear this issue 
LinkFinder/linkfinder.py:133: DeprecationWarning: ssl.PROTOCOL_TLSv1_2 is deprecated
sslcontext = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)

**Comment by Archurcl4w** [comment]
> python -W ignore linkfinder.py

Can't fix with this or please reproduce the step . Any solution ?

**Comment by L3V14TH4N** [comment]
> This issue was fixed by the pull request update for latest #133 . Change the old depreciated function as per this Files changed:- try: sslcontext = ssl.create_default_context() response = urlopen(q, timeout=args.timeout, context=sslcontext) except: sslcontext = ssl.create_default_context() response = urlopen(q, timeout=args.timeout, context=sslcontext)
> 
> This issue can close now.

It worked perfectly here. Thanks!

**Comment by quydox** [comment]
I change urlopen to requests lib then it works well

**Comment by GerbenJavado** [comment]
Fixed by 1debac5dace4724fd6187c06f133578dae51c86f
