### ISSUE TITLE
Problem "SSL: CERTIFICATE_VERIFY_FAILED"

### ISSUE THREAD

**Issue by L3V14TH4N** [GerbenJavado/LinkFinder#134]
Hi,
I'm having the following problem when running the tool:

sudo python3 linkfinder.py -i https://<site.com>/ -d

```
Usage: python linkfinder.py [Options] use -h for help
Error: invalid input defined or SSL error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
```
Some help?

**Comment by Archurcl4w** [comment]
Hello the same command  you use works for me and no problem having like that in mine.  Go the other issue #122  
{https://github.com/GerbenJavado/LinkFinder/issues/122} and check for my comment at the last which fixed that problem.  Likewise check your code after line no. 132  at linkfinder.py in yours whether it is same as following 
`try:
     sslcontext = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
`
 if this what you have then change it to as per my comment in #122
