### ISSUE TITLE
error after running it it related to sslcontext = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)

### ISSUE THREAD

**Issue by SecuritySphinx** [GerbenJavado/LinkFinder#141]
┌──(root㉿kali)-[~/Tool/LinkFinder]
└─# python linkfinder.py -i https://domain/trading/assets/js/88798/datatables.min.js -o dash.html
/root/Tool/LinkFinder/linkfinder.py:133: DeprecationWarning: ssl.PROTOCOL_TLSv1_2 is deprecated
  sslcontext = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
                                                                                                                                                             
libEGL warning: DRI2: failed to authenticate
┌──(root㉿kali)-[~/Tool/LinkFinder]
└─# Missing chrome or resource URL: resource://gre/modules/UpdateListener.jsm
Missing chrome or resource URL: resource://gre/modules/UpdateListener.sys.mjs
Missing chrome or resource URL: resource://gre/modules/UpdateListener.jsm
Missing chrome or resource URL: resource://gre/modules/UpdateListener.sys.mjs

**Comment by mkannan22** [comment]
same issue

**Comment by meiadnoushadi** [comment]
![Screenshot_2023-11-14_17-15-23](https://github.com/GerbenJavado/LinkFinder/assets/99072256/594b3de8-84f5-4b0b-830e-aa5df589d39a)
change line 133, 137
`sslcontext = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)`
add line 134, 138|
`sslcontext.load_verify_locations("/etc/ssl/certs/ca-certificates.crt")`
locations is path to file ssl certification in system

**Comment by GerbenJavado** [comment]
Fixed by 1debac5dace4724fd6187c06f133578dae51c86f
