### ISSUE TITLE
Error: invalid input defined or SSL error: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:1006)>

### ISSUE THREAD

**Issue by Dxter95** [GerbenJavado/LinkFinder#146]
Error: invalid input defined or SSL error: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:1006)>

how to fix it please

**Comment by GerbenJavado** [comment]
Fixed by 1debac5dace4724fd6187c06f133578dae51c86f
