### ISSUE TITLE
DeprecationWarning: ssl.PROTOCOL_TLSv1_2 is deprecated   sslcontext = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)

### ISSUE THREAD

**Issue by mikykatwal** [GerbenJavado/LinkFinder#147]
i have created a txt file  
validdomain.txt 
there is a website link https://amazon.com
https://amazon.sg
when i try to run the program it is not displaying anything 
python3 linkfinder.py -i validdomain.txt -d -o cli
/home/user/subdomaintool/LinkFinder/linkfinder.py:133: DeprecationWarning: ssl.PROTOCOL_TLSv1_2 is deprecated
  sslcontext = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)

**Comment by w4spy** [comment]
> i have created a txt file validdomain.txt there is a website link https://amazon.com https://amazon.sg when i try to run the program it is not displaying anything python3 linkfinder.py -i validdomain.txt -d -o cli /home/user/subdomaintool/LinkFinder/linkfinder.py:133: DeprecationWarning: ssl.PROTOCOL_TLSv1_2 is deprecated sslcontext = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)

import certifi
then go to line 133 and 136
change sslcontex with 
sslcontext = ssl.create_default_context(cafile=certifi.where())
should work

**Comment by GerbenJavado** [comment]
Fixed by 1debac5dace4724fd6187c06f133578dae51c86f
