### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by arbazkiraak** [GerbenJavado/LinkFinder#19]
@EdOverflow @GerbenJavado 

* First of All Thanks for Creating this Tool. 

How about Adding This Feature : 

All *.js urls in input.txt file.

Some JS File's may require Session Cookie : 

./linkfinder.py -cookie="SESSION" -i input.txt -o res.html

----------------------------------------------------------------------------------

Make's Request to *.js url.
takes the response.
find links 
and output it.
-------------------

Let me know if it is good idea .

Thanks!

**Comment by EdOverflow** [comment]
@arbazkiraak Thank you for the request. I will give it ago and see how it works. 

<details>
   <summary>
      P.S.:
   </summary>
    I did not create this tool. :wink: 
</details>

**Comment by arbazkiraak** [comment]
:dancer:  I Think this is great idea .

> EX: 

if you are testing with Burp Suite 

1. Click on Filter .
2. Filter by File extension . Show Only (add  js) on it.
3. this will show only .js files of our target .
4. finally select all content's as "Copy selected url's"
5. paste it in a file.
6. give it to linkfinder.py with cookie header.

profit !

Let me know what do you think :)

**Comment by GerbenJavado** [comment]
Haha @EdOverflow it is close to being just as much of your project as it is mine. @arbazkiraak Looks good, great ideas. Im on holidays tomorrow, might just implement it then.

**Comment by arbazkiraak** [comment]
@GerbenJavado  :1st_place_medal:    , Looking forward to contribute to it. 



https://twitter.com/ArbazKiraak

**Comment by GerbenJavado** [comment]
@arbazkiraak I like the `All *.js urls in input.txt file.` and the Burp option the best. For the Burp option I have a suggestion, wouldn't it be better if I implemented an option where LinkFinder takes `Save selected items` and reads the JS files in that file. This was the output is already there and cookies aren't a issue.

**Comment by arbazkiraak** [comment]
@GerbenJavado  Thanks for the Response.

"Save selected items" Yes This is Better Option :+1:   Than Previous one .

Can we put both Feature's ? 

1.  "Save selected items" if you are Testing From Burp suites.
2.   --cookie extra parameter  And to read All *.js urls in input.txt file. Because Not Everyone use's burp + it will good for testing quickly (Mainly for Authenticated JS Files) . directly copying url from browser and trying with cookie paramter with Linkfinder . 


Do let me know What do you think and  how you can going to code this feature . 

Thanks!

**Comment by GerbenJavado** [comment]
@arbazkiraak probably will take that route indeed. 1rst one will have my priority. Coding shouldnt be a problem but if you are interested in how I am going to do it, chat with me on twitter or the bugbountyforum/bougbounty-world slack.

**Comment by GerbenJavado** [comment]
@arbazkiraak Burp intergration and cookie support has been merged today. Can you confirm whether or not this works correctly (seems to do so here) ?

**Comment by arbazkiraak** [comment]
Hi, 

i Confirm Both are Working !

Thanks :1st_place_medal:
