### ISSUE TITLE
Output HTML can't be saved due to UnicodeEncodeError exception: 'ascii' codec can't encode character u'\u2018'

### ISSUE THREAD

**Issue by bl4de** [GerbenJavado/LinkFinder#2]
Hi Gerben,

First things first - thank you for such great tool :) I've just started to use it ;)

Unfortunately, I've stuck with an error thrown by UnicodeEncodeError while HTML with output is saved to output file (sorry for url redacted, but it comes from private BB program and I can't disclose it - basically it's just big, minified JavaScript file, full of juicy endpoint URLs)

Here's how I call your script:

```
bl4de:~/hacking/tools/LinkFinder $ ./linkfinder.py -i https://[REDACTED]/script.js
```

And the result is:

```
Traceback (most recent call last):
  File "./linkfinder.py", line 132, in <module>
    text_file.write(html)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 71461: ordinal not in range(128)
bl4de:~/hacking/tools/LinkFinder $
```

\u2018 is Unicode Character 'LEFT SINGLE QUOTATION MARK' (http://www.fileformat.info/info/unicode/char/2018/index.htm). When I've tried to look for it in JS file, I found it's just regular \u0027 (apostrophe). 

I found how to (probably) resolve such issues in this StackOverflow thread:

https://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20

For now, I've just made a quick workaround for this using try...except:

```Python
try:
    text_file = open(args.output, "w")
    text_file.write(html)
    text_file.close()
    print("URL to access output: file:///%s" % os.path.abspath(args.output))
except UnicodeEncodeError, e:
    print("Output can't be saved in {} due to exception: {}".format(args.output, e))
    
```

If you'd like to I can try to provide PR with fix for this issue :)

Regards,

bl4de

**Comment by GerbenJavado** [comment]
Hi bl4de! Thanks for the feedback. Using str.encode('utf-8') should have fixed this. Can you confirm whether: https://github.com/GerbenJavado/LinkFinder/commit/89771be1f7153f76c5c30012a64bd0dd0d1206fc fixed this or not?

**Comment by GerbenJavado** [comment]
Aah the fix seems incomplete for Python3 I'll further investigate

**Comment by bl4de** [comment]
Hi Gerben,

On macOS/Python 2.7.10 I can confirm it's fixed 👍
