### ISSUE TITLE
Remove duplicates endpoints ( cli / html )

### ISSUE THREAD

**Issue by TvMpt** [GerbenJavado/LinkFinder#24]
Sometimes duplicate data is useful, but not in this case, I think. Could be better if you remove all duplicated entries in endpoints list [ ], before send to output ( cli/html )

**Comment by GerbenJavado** [comment]
Hi @TvMpt. Thank you for addressing this bug/feature. This is already happening for cli mode but not for html output. This will be addressed.

**Comment by GerbenJavado** [comment]
@TvMpt This issue should be fixed. See commit: https://github.com/GerbenJavado/LinkFinder/commit/a5fa9bfeee02d4a4672e5eb1c1442dbfba197880
