### ISSUE TITLE
OSError: [WinError 6] The handle is invalid

### ISSUE THREAD

**Issue by gopinath6** [GerbenJavado/LinkFinder#28]
OS: Win 7
python  :3
I tried to use burp  save  items to find link
Eventhough output file was created.Any idea about the error in console?

![image](https://user-images.githubusercontent.com/6551119/36634374-874d9be0-19c9-11e8-99b6-f35b19e629fb.png)

**Comment by GerbenJavado** [comment]
Hi @gopinath6, if you feed a Burp file into LinkFinder make sure to use the output option cli. This can be done by setting adding: "-o cli" at the end. Hope this helps. Kind regards, Gerben

**Comment by GerbenJavado** [comment]
Hi @gopinath6, Do I understand you correctly that the output was complete? I'll look into the error.

**Comment by gopinath6** [comment]
Yes you are correct, am getting the output file completed and  also the error.
-o cli  also works, but not  easily readable format.

**Comment by GerbenJavado** [comment]
Should be fixed now ;) (finally)
