### ISSUE TITLE
Dealing with SSL errors

### ISSUE THREAD

**Issue by ctgreen78** [GerbenJavado/LinkFinder#30]
Any way to deal with sites that use self-sign certs?
 
![linkfinder](https://user-images.githubusercontent.com/34352828/38510533-5bd65ef6-3bf3-11e8-83da-4f4913e790ed.JPG)

**Comment by GerbenJavado** [comment]
I'll look into it. Thanks!

Op ma 9 apr. 2018 18:41 schreef ctgreen78 <notifications@github.com>:

**Comment by ctgreen78** [comment]
Thanks!

**Comment by GerbenJavado** [comment]
Could you verify if this code change (https://github.com/GerbenJavado/LinkFinder/pull/31) fixes the issue?

**Comment by pygain11** [comment]
Usage: python linkfinder.py [Options] use -h for help
Error: invalid input defined or SSL error: <urlopen error [Error 3] : ''>
