### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by samuel823** [GerbenJavado/LinkFinder#35]
when im using ./linkfinder -i target.com < it is working
but when i try to scan with a file , and then the file has like 20 url from the target site than is not working idk why

**Comment by samuel823** [comment]
so that my question how can i scan with a file , and the file have so many url inside , sorry for my bad english

**Comment by GerbenJavado** [comment]
Hi @samuel823, The documentation should provide you with enough information on how to scan a local file using LinkFinder. Furthermore try the '-o cli' options for non-JS files.

**Comment by samuel823** [comment]
so that i put ./linkfinder -i -o *.txt < the file with url. right?
