### ISSUE TITLE
Regular expression problem

### ISSUE THREAD

**Issue by sftrwo** [GerbenJavado/LinkFinder#52]
Regular expressions may not be perfect enough, some urls cannot match.
for example:
` var url=get_path_url("?mod=admin&act=login&method=ajax);`

If I put index.php in front of "?", I can match it.
for example:
` var url=get_path_url("index.php?mod=admin&act=login&method=ajax);`

**Comment by GerbenJavado** [comment]
This is expected behaviour since the latter Url will be hard to catch, you are more than welcome to write support for it that doesn't introduce many false positives.
