### ISSUE TITLE
TypeError: string indices must be integers, not str

### ISSUE THREAD

**Issue by vectorinfosec** [GerbenJavado/LinkFinder#54]
```
python linkfinder.py -i https://www.fly.com/  -b -o cli
Traceback (most recent call last):
  File "linkfinder.py", line 326, in <module>
    file = url['js']
TypeError: string indices must be integers, not str
```

**Comment by EdOverflow** [comment]
Drop the `-b` flag and everything should work. The `-b` flag is reserved for when you want to supply LinkFinder with a Burp file as input as stated in the README.md:

> Toggle to use when inputting a Burp 'Save selected' file containing multiple JS files

**Comment by EdOverflow** [comment]
@GerbenJavado, might be worth throwing an error whenever the `-b` flag is used in conjunction with a URL from stdin.

**Comment by vectorinfosec** [comment]
sorry, wrongly i typed -b instead of -d. thanks
