### ISSUE TITLE
ImportError: No module name html

### ISSUE THREAD

**Issue by vishnugadupudi** [GerbenJavado/LinkFinder#67]
Traceback (most recent call last):
  File "linkfinder.py", line 11, in <module>
    import re, sys, glob, html, argparse, jsbeautifier, webbrowser, subprocess, base64, ssl, xml.etree.ElementTree
ImportError: No module named html

**Comment by vishnugadupudi** [comment]
Solution: pip install html
                       or
               sudo apt-get install html

**Comment by EdOverflow** [comment]
:+1:

**Comment by hasnat0x01** [comment]
`python linkfinder.py -i http://xxxx/js/hoverIntent.js -o results.html
Traceback (most recent call last):
  File "linkfinder.py", line 372, in <module>
    ''' % (html.escape(url), html.escape(url))
AttributeError: 'module' object has no attribute 'escape'`

any solution for this error ?

**Comment by EdOverflow** [comment]
@hasnat0x01, make sure you are running Python 3.

**Comment by hasnat0x01** [comment]
@EdOverflow Thank you its working fine now

**Comment by IbrahimGithub** [comment]
Install before requirement file, use this command for install pip
sudo apt install python-pip
