### ISSUE TITLE
Getting error while using burp file

### ISSUE THREAD

**Issue by sridharm17** [GerbenJavado/LinkFinder#81]
$ python3 linkfinder.py -b -i /home/kindred.burp -o cli
Traceback (most recent call last):
  File "linkfinder.py", line 325, in <module>
    urls = parser_input(args.input)
  File "linkfinder.py", line 98, in parser_input
    items = xml.etree.ElementTree.fromstring(open(args.input, "r").read())
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 1: invalid start byte

$ python3 --version
Python 3.8.3

**Comment by n00py** [comment]
You don't use a .burp file, you use an export. Right click your scope and click "Save selected items"
