### ISSUE TITLE
Can't load .js files from the folder.

### ISSUE THREAD

**Issue by 0xDexter0us** [GerbenJavado/LinkFinder#89]
I have downloaded .js files from gau then I want to process it with this script.
But it just dumps the names of all files on cli and doesn't works.

Command I tried.

```  python3 SecretFinder.py -i ../location/to/jsfiles/*  ```

```  python3 SecretFinder.py -i ../location/to/jsfiles/  ```

**Comment by 0xDexter0us** [comment]
So sorry I posted this here by mistake...

Very very sorry

**Comment by EdOverflow** [comment]
No worries, @0xDexter0us. :)
