### ISSUE TITLE
error with ssl 

### ISSUE THREAD

**Issue by dennismzia** [GerbenJavado/LinkFinder#91]
hi im getting this error when i run ``` invalid input defined or SSL error: <urlopen error [SSL] internal error```
after installation it was running fine maybe its  something to do with the urlopener function 
thanks in advance.

**Comment by learn-alam** [comment]
hi...
What is  http status of your input url of js files.
It will work on 200 ok status.
Following url has 200ok status.
linkfinder -i https://www.example.com/voucher/gtm.js

**Comment by GerbenJavado** [comment]
Likely fixed with 1debac5dace4724fd6187c06f133578dae51c86f

**Comment by dennismzia** [comment]
I have just checked and confirmed that it's fixed. Thank you if anything I find this tool easy to use and integrate into my workflows as opposed to all other tools out there doing similar work
