### ISSUE TITLE
How to execute linkfinder as a command in terminal from anywhere ?

### ISSUE THREAD

**Issue by abhi06991** [GerbenJavado/LinkFinder#96]
I am just trying to include the path of the linkfinder.py to .bashrc file, so that I can run it as a linux command from anywhere, but its just not working!

I have tried everything, gave the script the +x permissions, removed the .py extension. When I am in the LinkFinder folder, this command works `./linkfinder` fine, but I am not able to run the command from anywhere else.

Any suggestions ?

**Comment by RapidEU** [comment]
I find the symbolic link a better solution.

For example, if I want to run dirsearch.py using the command 'dirsearch' from anywhere I do this:

`sudo ln -s /home/kali/dirsearch/dirsearch.py dirsearch`

Then I can run 'dirsearch' from any directory.

**Comment by rickjms1337** [comment]
you can also set an alias in your `.bashrc` or you `.zshrc` file for example this is how i set mine up had issues with installing it. once you set this just source your `.bashrc` file / restart terminal should work.

```bash
alias linkfinder='python3 /home/rickjms/github-tools/LinkFinder/linkfinder.py'
```
