### ISSUE TITLE
ImportError: No module named html

### ISSUE THREAD

**Issue by HackerAndya** [GerbenJavado/LinkFinder#97]
Hey, It's giving many errors while installing and working with the tool. So I would like to ask for regex of grep so that I can make my own

**Comment by HackerAndya** [comment]
while executing linkfinder.py , I'm getting below error. Though I install requirements


Traceback (most recent call last):
  File "linkfinder.py", line 11, in <module>
    import re, sys, glob, html, argparse, jsbeautifier, webbrowser, subprocess, base64, ssl, xml.etree.ElementTree
ImportError: No module named html

**Comment by w1th0ut** [comment]
are you sure already install requirements.txt?
```
python3 -m pip install -r requirements.txt
python3 linkfinder.py -h
```

**Comment by EdOverflow** [comment]
Closing as duplicate of #75.
