### ISSUE TITLE
ssl error http/2

### ISSUE THREAD

**Issue by w1th0ut** [GerbenJavado/LinkFinder#98]
```
python3 .\linkfinder.py -i https://domain.com/js/main.js
Error: invalid input defined or SSL error: HTTP/2
```
I am facing this issue, any idea?

**Comment by channyein1337** [comment]
run like this : ```python3 linkfinder.py -i https://domain.com/js/main.js -o cli```

**Comment by w1th0ut** [comment]
```
python3 .\linkfinder.py -i https://domain.com/js/main.js -o cli
Usage: python .\linkfinder.py [Options] use -h for help
Error: invalid input defined or SSL error: HTTP/2
```

still same

**Comment by channyein1337** [comment]
It is still going or just stop with this errors?

**Comment by w1th0ut** [comment]
stopping with this error, I running on windows 10 btw

**Comment by channyein1337** [comment]
I am not sure what is the error but it is working fine for me. I am running on linux wsl in windows.

**Comment by w1th0ut** [comment]
Problem solved, I forgot to turn off my proxy. That why this error happened, thanks @channyein1337 for taking time to help me 😄
